coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

  ignore:
    - "spec/**/*"
    - "lib/vectra/version.rb"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
