require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'lib/generators/**/templates/**/*'

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#' # Allow long comment lines

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'vectra.gemspec'
    - 'Rakefile'
    - 'benchmarks/**/*'
  ExcludedMethods:
    - 'included'
    - 'class_methods'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 7
  CountKeywordArgs: false

# Style
Style/Documentation:
  Enabled: false # We use YARD documentation

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false # Allow both single and double quotes

Style/ArgumentsForwarding:
  Enabled: false # Ruby 3.2+ feature, but not required

Style/IfUnlessModifier:
  Enabled: false # Allow multi-line if/unless for clarity

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# Naming
Naming/MethodParameterName:
  AllowedNames:
    - id
    - to
    - db
    - io

# Lint
Lint/MissingSuper:
  Enabled: false # Allow classes without super calls

Lint/ScriptPermission:
  Enabled: false

# RSpec specific
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - 'spec/integration/**/*'

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false # Allow both have_received and receive

RSpec/IdenticalEqualityAssertion:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false # Allow string descriptions

# Disable problematic Capybara cop
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Naming
Naming/MemoizedInstanceVariableName:
  Enabled: false # Allow descriptive names

# Layout
Layout/LineLength:
  Max: 185
  Exclude:
    - 'vectra.gemspec'

# Additional disables for auto-correctable minor issues
Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MapIntoArray:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Naming/PredicateName:
  Enabled: false  # Allow has_vector DSL method

Gemspec/OrderedDependencies:
  Enabled: false
