name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize client with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The operation should succeed and return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I got an error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue
      render: ruby
      placeholder: |
        require 'vectra'

        client = Vectra.pinecone(api_key: "...", environment: "...")
        # ...
    validations:
      required: false

  - type: dropdown
    id: provider
    attributes:
      label: Vector Database Provider
      description: Which provider are you using?
      options:
        - Pinecone
        - Qdrant
        - Weaviate
        - Other
    validations:
      required: true

  - type: input
    id: vectra-version
    attributes:
      label: Vectra Version
      description: Which version of Vectra are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: ruby-version
    attributes:
      label: Ruby Version
      description: Output of `ruby --version`
      placeholder: "ruby 3.2.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 14.0, Ubuntu 22.04, etc."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Error logs, stack traces, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
