# frozen_string_literal: true

require "rails/generators/base"

module Vectra
  module Generators
    # Rails generator for creating a vectra-enabled index for a model.
    #
    # @example
    #   rails generate vectra:index Product embedding dimension:1536 provider:qdrant
    #
    # This will:
    # - Generate a pgvector migration (when provider=pgvector)
    # - Create a model concern with `has_vector`
    # - Update the model to include the concern
    # - Append an entry to config/vectra.yml (no secrets)
    class IndexGenerator < Rails::Generators::Base
      argument :model_name, type: :string, banner: "ModelName"
      argument :column_name, type: :string, default: "embedding", banner: "column_name"

      class_option :dimension, type: :numeric, default: 1536,
                               desc: "Vector dimension (e.g. 1536 for OpenAI)"
      class_option :provider, type: :string, default: "qdrant",
                              desc: "Vector provider (qdrant, pgvector, pinecone, weaviate, memory)"
      class_option :index, type: :string, default: nil,
                           desc: "Index/collection name (defaults to table name)"

      def create_migration_for_pgvector
        return unless provider_name == "pgvector"

        timestamp = Time.now.utc.strftime("%Y%m%d%H%M%S")
        file_name = "#{timestamp}_add_#{column_name.underscore}_to_#{table_name}.rb"
        path = File.join("db/migrate", file_name)

        migration_body = <<~RUBY
          class Add#{column_name.camelize}To#{table_name.camelize} < ActiveRecord::Migration#{migration_version}
            def change
              add_column :#{table_name}, :#{column_name}, :vector, limit: #{dimension}
            end
          end
        RUBY

        create_file(path, migration_body)
      end

      def create_model_concern
        path = File.join("app/models/concerns", "#{model_name.underscore}_vector.rb")

        concern_body = <<~RUBY
          # frozen_string_literal: true

          module #{concern_module_name}
            extend ActiveSupport::Concern

            included do
              include Vectra::ActiveRecord

              has_vector :#{column_name},
                         provider: :#{provider_name},
                         index: "#{index_name}",
                         dimension: #{dimension}
            end
          end
        RUBY

        create_file(path, concern_body)
      end

      def update_model_file
        path = File.join("app/models", "#{model_name.underscore}.rb")

        unless File.exist?(path)
          create_file(
            path,
            <<~RUBY
              # frozen_string_literal: true

              class #{model_name.camelize} < ApplicationRecord
                include #{concern_module_name}
              end
            RUBY
          )
          return
        end

        content = File.read(path)
        return if content.include?("include #{concern_module_name}")

        new_content = content.sub(/end\s*\z/, "  include #{concern_module_name}\nend\n")
        File.write(path, new_content)
      end

      def update_vectra_config
        path = File.join("config", "vectra.yml")

        existing = File.exist?(path) ? File.read(path) : ""
        entry_key = "#{table_name}:"

        return if existing.include?(entry_key)

        header = +"# Vectra index configuration (do NOT store API keys here)\n"
        header << "# Generated by vectra:index for #{model_name}\n\n"

        config_body = <<~YAML
          #{table_name}:
            provider: #{provider_name}
            index: #{index_name}
            dimension: #{dimension}

        YAML

        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, "#{existing.presence || header}#{config_body}")
      end

      private

      def table_name
        model_name.underscore.pluralize
      end

      def provider_name
        options[:provider].to_s
      end

      def index_name
        (options[:index] || table_name).to_s
      end

      def dimension
        options[:dimension].to_i
      end

      def migration_version
        "[#{Rails::VERSION::MAJOR}.#{Rails::VERSION::MINOR}]"
      end
    end
  end
end

